;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ac-pcmp/self-insert-command-with-ac-start
	c/mark-previous-like-this
	hungry-delete-backward
	hungry-delete-forward
	indent-new-comment-line
	mark-word
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	iedit-switch-to-mc-mode
	sp-next-sexp
	undo-tree-visualize
	))
